# Generated by Django 4.1.1 on 2022-10-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='fechaNacimiento',
            new_name='nac',
        ),
    ]
